INSERT INTO `universidad`.`paises` (`descripcion`) VALUES ('Argentina');
INSERT INTO `universidad`.`paises` (`descripcion`) VALUES ('Brasil');
INSERT INTO `universidad`.`paises` (`descripcion`) VALUES ('Uruguay');
INSERT INTO `universidad`.`paises` (`descripcion`) VALUES ('Chile');
INSERT INTO `universidad`.`paises` (`descripcion`) VALUES ('Paraguay');

INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Buenos Aires', '1');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Córdoba', '1');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Santa Fé', '1');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Santiago del Estero', '1');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Tucumán', '1');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Rio de Janeiro', '2');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Mato Grosso', '2');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Minas Gerais', '2');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Bahía', '2');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Goiás', '2');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Colonia', '3');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('San José', '3');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Canelones', '3');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Montevideo', '3');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Maldonado', '3');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Santiago', '4');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('La Serena', '4');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Cuyo', '4');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Chillán', '4');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Concepción', '4');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Asunción', '5');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Concepción', '5');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('San Pedro', '5');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Cordillera', '5');
INSERT INTO `universidad`.`provincias` (`descripcion`, `idPais`) VALUES ('Guairá', '5');

INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('General Pacheco', '1');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('José C. Paz', '1');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Munro', '1');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Olavarria', '1');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('El Talar', '1');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Achiras', '2');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Balnearia', '2');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Chazón', '2');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Córdoba', '2');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Cosquín', '2');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Rosario', '3');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Rafaela', '3');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Villa Gobernador Gálvez', '3');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Arroyo Seco', '3');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Venado Tuerto', '3');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Añatuya', '4');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Bandera', '4');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Frias', '4');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('La Banda', '4');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Pinto', '4');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Yerba Buena', '5');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Villa Nougues', '5');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('San Javier Tucuman', '5');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Raco', '5');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('El Cadillal', '5');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Copacabana', '6');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Ipanema', '6');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Botafogo', '6');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Leme', '6');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Flamengo', '6');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Cuiabá', '7');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Várzea Grande', '7');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Rondonópolis', '7');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Sinop', '7');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Tangará da Serra', '7');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Ibertioga', '8');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Ibiá', '8');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Ibirité', '8');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Ibitiúra de Minas', '8');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Iguatama', '8');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Salvador de Bahía', '9');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Feira de Santana', '9');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Vitória da Conquista', '9');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Camaçari', '9');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Juazeiro', '9');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Goiânia', '10');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Anápolis', '10');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Rio Verde', '10');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Luziânia', '10');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Itumbiara', '10');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Agraciada', '11');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('El Semillero', '11');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Britópolis', '11');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Puerto Inglés', '11');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('El Ensueño', '11');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Arazatí', '12');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Rafael Perazza', '12');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Kiyú', '12');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('La Boyada', '12');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Scavino', '12');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('18 de Mayo​', '13');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Aguas Corrientes', '13');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Atlántida', '13');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Barros Blancos', '13');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Canelones', '13');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES (' Belvedere', '14');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('La Teja', '14');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Paso Molino', '14');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Aires Puros', '14');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Cuchilla Pereyr', '14');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Aiguá', '15');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Garzón', '15');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('José Ignacio', '15');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('La Barra', '15');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Maldonado', '15');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Cerro Navia', '16');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('La Cisterna', '16');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('La Granja', '16');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('San Miguel', '16');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('San Joaquín', '16');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Cerro Grande', '17');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('El Milagro', '17');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Algarrobito', '17');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Puertas del Mar', '17');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Peñuelas', '17');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('San Juan Ciudad', '18');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Barreal', '18');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Villa San Agustín', '18');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Rodeo', '18');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Calingasta', '18');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Chillán', '19');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Quinchamalí', '19');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Las Mariposas', '19');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Quinquehua', '19');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Santa Clara', '19');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Concepción', '20');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES (' San Pedro de la Paz', '20');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Chiguayante', '20');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Talcahuano', '20');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Hualpén', '20');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Areguá', '21');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Capiatá', '21');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Fernando de la Mora', '21');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Guarambaré', '21');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Itá', '21');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Concepción', '22');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Horqueta', '22');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Yby Yaú', '22');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Loreto', '22');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Belén', '22');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('San Pedro de Ycuamandiyú', '23');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Itacurubí del Rosario', '23');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Nueva Germania', '23');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Tacuatí', '23');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Choré', '23');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Altos', '24');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Atyrá', '24');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Piribebuy', '24');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Santa Elena', '24');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Valenzuela', '24');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Doctor Botrell', '25');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES (' Mbocayaty del Guairá', '25');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Ñumí', '25');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Borja', '25');
INSERT INTO `universidad`.`localidades` (`descripcion`, `idProvincia`) VALUES ('Félix Pérez Cardozo', '25');

INSERT INTO `universidad`.`carrera` (`descripcion`) VALUES ('Técnico Universitario en Programación');
INSERT INTO `universidad`.`carrera` (`descripcion`) VALUES ('Técnico Universitario en Sistemas');
INSERT INTO `universidad`.`carrera` (`descripcion`) VALUES ('Ingenieria Mecánica');
INSERT INTO `universidad`.`carrera` (`descripcion`) VALUES ('Ingenieria Eléctrica');
INSERT INTO `universidad`.`carrera` (`descripcion`) VALUES ('Ingenieria Automotríz');

INSERT INTO `universidad`.`materias` (`descripcion`) VALUES ('Laboratorio IV');
INSERT INTO `universidad`.`materias` (`descripcion`) VALUES ('Diseño y Administracion de DB');
INSERT INTO `universidad`.`materias` (`descripcion`) VALUES ('Práctica Supervisada');
INSERT INTO `universidad`.`materias` (`descripcion`) VALUES ('Legislación');
INSERT INTO `universidad`.`materias` (`descripcion`) VALUES ('Metodología de Sistemas I');

INSERT INTO `universidad`.`materiasxcarrera` (`idCarrera`, `idMateria`) VALUES ('1', '1');
INSERT INTO `universidad`.`materiasxcarrera` (`idCarrera`, `idMateria`) VALUES ('1', '2');
INSERT INTO `universidad`.`materiasxcarrera` (`idCarrera`, `idMateria`) VALUES ('2', '3');
INSERT INTO `universidad`.`materiasxcarrera` (`idCarrera`, `idMateria`) VALUES ('2', '4');
INSERT INTO `universidad`.`materiasxcarrera` (`idCarrera`, `idMateria`) VALUES ('3', '5');
INSERT INTO `universidad`.`materiasxcarrera` (`idCarrera`, `idMateria`) VALUES ('3', '1');
INSERT INTO `universidad`.`materiasxcarrera` (`idCarrera`, `idMateria`) VALUES ('4', '2');
INSERT INTO `universidad`.`materiasxcarrera` (`idCarrera`, `idMateria`) VALUES ('4', '3');
INSERT INTO `universidad`.`materiasxcarrera` (`idCarrera`, `idMateria`) VALUES ('5', '4');
INSERT INTO `universidad`.`materiasxcarrera` (`idCarrera`, `idMateria`) VALUES ('5', '5');

INSERT INTO `universidad`.`alumnos` (`dni`, `legajo`, `nombre`, `apellido`, `fechaNacimiento`, `idNacionalidad`, `domicilio`, `idLocalidad`, `email`, `telefono`, `estado`) VALUES ('11111111', '2000', 'Pablo Francisco', 'Bulacio', '1979-07-24', '1', 'Olavarria 2843', '5', 'pfbulacio@hotmail.com', '1133668802', '1');
INSERT INTO `universidad`.`alumnos` (`dni`, `legajo`, `nombre`, `apellido`, `fechaNacimiento`, `idNacionalidad`, `domicilio`, `idLocalidad`, `email`, `telefono`, `estado`) VALUES ('22222222', '2001', 'Nicolas ', 'Nuñez', '2000-06-26', '1', 'El Salvador 1547', '1', 'nnuñez@yahoo.com.ar', '1125368965', '1');
INSERT INTO `universidad`.`alumnos` (`dni`, `legajo`, `nombre`, `apellido`, `fechaNacimiento`, `idNacionalidad`, `domicilio`, `idLocalidad`, `email`, `telefono`, `estado`) VALUES ('33333333', '2002', 'Federico Ivan', 'Parrotta', '1998-03-02', '1', 'Av. SiempreViva 742', '2', 'fiparrotta@gmail.com', '1150234658', '1');
INSERT INTO `universidad`.`alumnos` (`dni`, `legajo`, `nombre`, `apellido`, `fechaNacimiento`, `idNacionalidad`, `domicilio`, `idLocalidad`, `email`, `telefono`, `estado`) VALUES ('44444444', '2003', 'Sebastián Iván', 'Puyelli Latour', '1995-08-17', '1', 'Av. Santa Fé 14526', '4', 'sipuyelli@hotmail.com', '1136254968', '1');
INSERT INTO `universidad`.`alumnos` (`dni`, `legajo`, `nombre`, `apellido`, `fechaNacimiento`, `idNacionalidad`, `domicilio`, `idLocalidad`, `email`, `telefono`, `estado`) VALUES ('55555555', '2004', 'Pablo Andrés', 'Rodriguez Olsavsky', '2001-10-29', '1', 'Elm Street 1428', '3', 'parodriguez@gmail.com', '1153695682', '1');

INSERT INTO `universidad`.`docentes` (`dni`, `legajo`, `nombre`, `apellido`, `fechaNacimiento`, `idNacionalidad`, `domicilio`, `idLocalidad`, `email`, `telefono`, `estado`) VALUES ('66666666', '1000', 'Herrera', 'Tamara', '1997-05-23', '1', 'Hipolito Yrigoyen 1452', '1', 'therrera@hotmail.com', '1132456856', '1');
INSERT INTO `universidad`.`docentes` (`dni`, `legajo`, `nombre`, `apellido`, `fechaNacimiento`, `idNacionalidad`, `domicilio`, `idLocalidad`, `email`, `telefono`, `estado`) VALUES ('77777777', '1001', 'Claudio', 'Fernandez', '1965-06-01', '1', 'Av. Delosprofesores 666', '5', 'cfernandez@gmail.com', '1135698741', '1');
INSERT INTO `universidad`.`docentes` (`dni`, `legajo`, `nombre`, `apellido`, `fechaNacimiento`, `idNacionalidad`, `domicilio`, `idLocalidad`, `email`, `telefono`, `estado`) VALUES ('88888888', '1002', 'Carlos Javier', 'Rodriguez', '1985-12-24', '1', 'Calzadilla 142', '4', 'cjrodriguez@yahoo.com.ar', '1155639857', '1');

INSERT INTO `universidad`.`cursos` (`idMateria`, `dniDocente`, `semestre`, `anio`) VALUES ('1', '66666666', '1', '2021');
INSERT INTO `universidad`.`cursos` (`idMateria`, `dniDocente`, `semestre`, `anio`) VALUES ('1', '77777777', '1', '2021');
INSERT INTO `universidad`.`cursos` (`idMateria`, `dniDocente`, `semestre`, `anio`) VALUES ('2', '88888888', '2', '2021');

INSERT INTO `universidad`.`alumnosxcursos` (`dniAlumno`, `idCurso`, `parcial_1`, `parcial_2`, `recuperatorio_1`, `recuperatorio_2`, `estadoAprobacion`) VALUES ('11111111', '100', '7', '7', '8', '8', '1');
INSERT INTO `universidad`.`alumnosxcursos` (`dniAlumno`, `idCurso`, `parcial_1`, `parcial_2`, `recuperatorio_1`, `recuperatorio_2`, `estadoAprobacion`) VALUES ('22222222', '101', '8', '8', '9', '9', '1');
INSERT INTO `universidad`.`alumnosxcursos` (`dniAlumno`, `idCurso`, `parcial_1`, `parcial_2`, `recuperatorio_1`, `recuperatorio_2`, `estadoAprobacion`) VALUES ('33333333', '102', '9', '9', '10', '10', '1');
INSERT INTO `universidad`.`alumnosxcursos` (`dniAlumno`, `idCurso`, `parcial_1`, `parcial_2`, `recuperatorio_1`, `recuperatorio_2`, `estadoAprobacion`) VALUES ('44444444', '100', '6', '6', '8', '8', '1');
INSERT INTO `universidad`.`alumnosxcursos` (`dniAlumno`, `idCurso`, `parcial_1`, `parcial_2`, `recuperatorio_1`, `recuperatorio_2`, `estadoAprobacion`) VALUES ('55555555', '101', '5', '5', '10', '10', '1');

INSERT INTO `universidad`.`tiposusuario` (`descripcion`) VALUES ('Administrador');
INSERT INTO `universidad`.`tiposusuario` (`descripcion`) VALUES ('Docente');

INSERT INTO `universidad`.`admins` (`dni`, `nombre`, `apellido`, `fechaNacimiento`, `idNacionalidad`, `domicilio`, `idLocalidad`, `email`, `telefono`, `estado`) VALUES ('66666666', 'Tamara', 'Herrera', '1997-05-23', '1', 'Hipolito Yrigoyen 1452', '1', 'therrera@hotmail.com', '1132456856', '1');
INSERT INTO `universidad`.`admins` (`dni`, `nombre`, `apellido`, `fechaNacimiento`, `idNacionalidad`, `domicilio`, `idLocalidad`, `email`, `telefono`, `estado`) VALUES ('77777777', 'Claudio', 'Fernandez', '1965-06-01', '1', 'Av. Delosprofesores 666', '5', 'cfernandez@gmail.com', '1135698741', '1');
INSERT INTO `universidad`.`admins` (`dni`, `nombre`, `apellido`, `fechaNacimiento`, `idNacionalidad`, `domicilio`, `idLocalidad`, `email`, `telefono`, `estado`) VALUES ('123', 'Admin', 'Fernandez', '1965-06-01', '1', 'Av. Delosprofesores 666', '5', 'cfernandez@gmail.com', '1135698741', '1');


INSERT INTO `universidad`.`usuarios` (`dni`, `tipoUsuario`, `pass`, `estado`) VALUES ('66666666', '1', '6666', '1');
INSERT INTO `universidad`.`usuarios` (`dni`, `tipoUsuario`, `pass`, `estado`) VALUES ('77777777', '2', '7777', '1');
INSERT INTO `universidad`.`usuarios` (`dni`, `tipoUsuario`, `pass`, `estado`) VALUES ('123', '1', '123', '1');



